Lesson two
AlexMalyan/educateJs pull request #2
Opened 2021-03-30 13:18 UTC by AlexMalyan

2021-04-02 13:55 UTC, Om1X requested changes

2021-04-02 13:55 UTC, Om1X commented on lesson_two.html
> +                    switch (a) {
у вас реализован вывод введенного числа а не последовательность от введенного до 15

2021-04-02 13:55 UTC, Om1X commented on lesson_two.html
> +                                result = arg1 / arg2;
не использовали функции из задачи выше

2021-04-13 15:45 UTC, Om1X requested changes

2021-04-13 15:45 UTC, Om1X commented on lesson4_ObjectJs/task_two_basketObject.html
> +      ['Aston Martin', 15000, 3]
товары должны быть объектами а не массивами

2021-04-13 16:30 UTC, AlexMalyan commented on lesson4_ObjectJs/task_two_basketObject.html
> +      ['Aston Martin', 15000, 3]
Принято переделаю

2021-04-16 15:35 UTC, merged